package com.ar.bankingmelisa.domain.models;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;

@Entity
@Data
// The @Entity annotation marks this class as an entity that can be persisted to a relational database.
public class Account {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // The @Id annotation specifies that the 'id' field is the primary key of the entity.
    // The @GeneratedValue annotation indicates that the value of the 'id' field will be automatically generated by the database.
    private Long id;

    private BigDecimal balance;
    // The 'balance' field represents the current balance of the account.

    @ManyToOne
    // The @ManyToOne annotation establishes a many-to-one relationship between the Account entity and the User entity.
    // It indicates that an Account is owned by a single User.
    private User owner;
    // The 'owner' field stores the reference to the User entity that owns the account.
}



