package com.ar.bankingmelisa.domain.models;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Data
// The @Entity annotation marks this class as an entity that can be persisted to a relational database.
public class Transfer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "transfer_id")
    // The @Id annotation specifies that the 'id' field is the primary key of the entity.
    // The @GeneratedValue annotation indicates that the value of the 'id' field will be automatically generated by the database.
    private Long id;

    private Long origin;
    // The 'origin' field represents the identifier of the account from which the transfer originates.

    private Long target;
    // The 'target' field represents the identifier of the account to which the transfer is targeted.

    private Date date;
    // The 'date' field stores the date and time when the transfer was made.

    private BigDecimal amount;
    // The 'amount' field represents the amount of money being transferred.
}


